### ISSUE TITLE
ARM Cortex M0 Support

### ISSUE THREAD

**Issue by bibletech55** [dmadison/FastLED_NeoPixel#1]
I'm interested in using this library to run my NeoPixels, but my board uses the SAMD21 (Atmel ATSAMD21G18A) processor. Does FastLED_NeoPixel support this microcontroller?

Here's a link to my board: https://tinycircuits.com/products/tinyzero-processor?variant=21137366515796

**Comment by dmadison** [comment]
The library is a wrapper for FastLED and has no board-specific support. For any questions about hardware compatibility please refer to the FastLED documentation.
