### ISSUE TITLE
Library does not compile for Adafruit Clue

### ISSUE THREAD

**Issue by xchg-dot-ca** [dmadison/FastLED_NeoPixel#3]
Library does not compile for Adafruit Clue
In same time when using directly #include <Adafruit_NeoPixel.h> all works
Attaching Log and working and non-working sketches

[strandtest-working.zip](https://github.com/dmadison/FastLED_NeoPixel/files/10026740/strandtest-working.zip)
[strandtest-not-working.zip](https://github.com/dmadison/FastLED_NeoPixel/files/10026741/strandtest-not-working.zip)
[log.txt](https://github.com/dmadison/FastLED_NeoPixel/files/10026742/log.txt)

**Comment by dmadison** [comment]
Hello. This library uses FastLED underneath, and FastLED does not support the Adafruit Clue.

If you need support for that board I recommend creating an issue on [the FastLED repo](https://github.com/fastled/fastled).
