### ISSUE TITLE
The library does not compile with esp8266 arduino core 3.1.2.

### ISSUE THREAD

**Issue by kabirwbt** [dmadison/FastLED_NeoPixel#5]
In esp8266 projects, the library does not compile and instead gives a warning which is attached in file submitted along with the bug report.
[fled_np.txt](https://github.com/dmadison/FastLED_NeoPixel/files/11958420/fled_np.txt)

The issue occurs at line 76 which is :
`else count = min(count, numLEDs - first);  // if both are set, fill from first to end without overrunning buffer
`
min function is overloaded in esp8266 projects. The solution is to use _min instead of min which makes the problem go away by using Arduino's macro for _min.

https://github.com/dmadison/FastLED_NeoPixel/pull/6

**Comment by dmadison** [comment]
Thank you for reporting this issue, it appears that this is a problem with how the `min` function is implemented between platforms.

**Comment by dmadison** [comment]
This compiles for ESP8266 using core 3.1.2 on my local machine but I have not tested it with a strip. Please test on your setup as well and feel free to reopen if you run into any problems.

Thanks for improving the library!

**Comment by kabirwbt** [comment]
@dmadison I compiled and ran your fixed version. It is working well as of now. Thank you for the fix.

**Comment by dmadison** [comment]
Perfect! Thank you for following up.
